### PR TITLE
added search bar

### PR DESCRIPTION
**Pull request by yzabeast1**

### CODE REVIEW

**Review by NSPC911 — CHANGES_REQUESTED** [review]
can you make it such that if there are more than 5 matches, it only shows 5 matches?

**Comment by NSPC911** [comment]
b36792612e8501fdaf389cd987b817d60142c17e
> chat he forgor 💀

**Review by NSPC911 — COMMENTED** [review]
wait need to load on my laptop

**Comment by yzabeast1** [comment]
> [b367926](https://github.com/BEComTweaks/behaviour-packs/commit/b36792612e8501fdaf389cd987b817d60142c17e)
> 
> > chat he forgor 💀

blame vscode for not detecting it as html

**Pull request merged**
